config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'flats#index'
  resources :flats, only: %i[index show edit destroy update create new]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/flat.rb
class Flat < ApplicationRecord
  validates :name, presence: true
  validates :address, presence: true
  validates :number_of_guests, presence: true, numericality: { greater_than: 0 }
  validates :price_per_night, presence: true, numericality: { greater_than: 0 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :set_flat, only: %i[show edit update destroy]

  def index
    @flats = Flat.all
  end

  def show
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    @flat.save
    redirect_to flat_path(@flat)
  end

  def edit
  end

  def update
    @flat.update(flat_params)
    redirect_to flat_path(@flat)
  end

  def destroy
    @flat.destroy
    redirect_to flats_path
  end

  private

  def set_flat
    @flat = Flat.find(params[:id])
  end

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_flat_card.html.erb
<div class="rounded-lg overflow-hidden w-[25rem] h-[25rem] bg-slate-200 shadow-md flex flex-col justify-between">
  <div class="w-full h-2/3 bg-cover bg-center" style="background-image: url('https://images.unsplash.com/photo-1494526585095-c41746248156?w=1200')">
  </div>

  <div class="p-3 flex flex-col gap-2 h-1/2">
    <%= link_to flat.name, flat_path(flat), class: 'text-2xl font-bold' %>
    <p class="text-sm"><%= flat.address %></p>
    <div class="flex gap-2">
      <div class="flex items-center gap-1">
        <i class="fa-solid fa-people-line"></i>
        <%= flat.number_of_guests %>
      </div>
      <div class="flex items-center gap-1">
        <i class="fa-solid fa-euro-sign"></i>
        <%= flat.price_per_night %>
      </div>
    </div>
  </div>

  <div class="h-fit p-4 flex justify-between items-center bg-slate-50">
    <%= link_to 'More info', flat_path(flat), class: 'bg-blue-500 text-white px-4 py-2 rounded-md hover:bg-blue-600' %>
    <%= link_to 'Edit', edit_flat_path(flat), class: 'bg-yellow-500 text-white px-4 py-2 rounded-md hover:bg-yellow-600' %>
    <%= link_to 'Delete', flat_path(flat), class: 'bg-red-500 text-white px-4 py-2 rounded-md hover:bg-red-600', data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' } %>
  </div>
</div>

app/views/flats/_form.html.erb
<%= simple_form_for @flat do |f| %>
  <%= f.input :name, input_html: { class: "flex flex-col mb-4" } %>
  <%= f.input :address, input_html: { class: "flex flex-col mb-4" } %>
  <%= f.input :number_of_guests, input_html: { class: "flex flex-col mb-4" } %>
  <%= f.input :price_per_night, input_html: { class: "flex flex-col mb-4" } %>
  <%= f.button :submit, class: "bg-green-500 text-white p-2 rounded-md hover:bg-green-600" %>
<% end %>

app/views/flats/edit.html.erb
<%= render "shared/banner" %>

<div class="flex justify-center">
  <div class="flex flex-col items-center mt-12 p-8 bg-slate-100 rounded-lg shadow-md">
    <h1 class="text-2xl mb-4">Edit flat</h1>
    <%= render "form" %>
  </div>
</div>

app/views/flats/index.html.erb
<%= render 'shared/banner' %>

<div class="flex flex-col items-center">
  <h1 class="text-4xl font-bold my-4 underline">All our flats :</h1>
  <div class="flex flex-col gap-4 w-full md:flex-row md:flex-wrap items-center justify-center">
    <% @flats.each do |flat| %>
      <%= render 'flat_card', flat: %>
    <% end %>
  </div>
</div>

app/views/flats/new.html.erb
<%= render "shared/banner" %>

<div class="flex justify-center">
  <div class="flex flex-col items-center mt-12 p-8 bg-slate-100 rounded-lg shadow-md">
    <h1 class="text-2xl mb-4">Add flat</h1>
    <%= render "form" %>
  </div>
</div>

app/views/flats/show.html.erb
<%= render 'shared/banner' %>

<div class="h-[350px] w-full bg-cover bg-center" style="background-image: url('https://images.unsplash.com/photo-1494526585095-c41746248156?w=1200')">

</div>

<div class="w-full flex justify-center">
  <div class="w-[65%] grid grid-cols-3 gap-4 -mt-24">
    <div class="col-span-2 flex flex-col gap-4">
      <div class="max-w-[2500px] bg-slate-100 rounded-lg shadow-md p-4 flex flex-col justify-center gap-2">
        <h1 class="text-4xl font-bold"><%= @flat.name %></h1>
        <p class="text-sm"><%= @flat.address %></p>
      </div>

      <div class="min-w-[350px] max-w-[2500px] bg-slate-100 rounded-lg shadow-md p-4 flex flex-col justify-center gap-2">
        <h2 class="text-2xl">A bit more about this flat...</h2>
        <p class="text-sm"><%= @flat.description %></p>
        <div class="h-[350px] bg-cover bg-center" style="background-image: url('https://a.storyblok.com/f/178460/1920x1000/394ad3b1e2/keeponmoving-webinar-slider-1920x1000px-desktop.jpg')"></div>
      </div>
    </div>

    <div class="col-span-1 flex flex-col gap-4">
      <div class="min-w-[150px] max-w-[2500px] bg-slate-100 rounded-lg shadow-md p-4 flex flex-col justify-center gap-2">
        <h3 class="underline">Book this place!</h3>
        <form action="#" class="flex flex-col gap-2">
          <input type="date" name="start_date" placeholder="Start date" class="p-2 rounded-md">
          <input type="date" name="end_date" placeholder="End date" class="p-2 rounded-md">
          <button type="submit" class="bg-green-500 text-white p-2 rounded-md hover:bg-green-600">Book</button>
        </form>
      </div>

      <div class="min-w-[150px] max-w-[2500px] bg-slate-100 rounded-lg shadow-md p-4 flex flex-col justify-center gap-2">
        <h3 class="text-2xl">Details</h3>
        <p class="text-sm"><%= @flat.number_of_guests %> guests</p>
        <p class="text-sm"><%= @flat.price_per_night %>€ per night</p>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main>
      <%= yield %>
    </main>
  </body>
</html>

app/views/shared/_banner.html.erb
<div class="bg-slate-200 p-2 h-16 flex items-center justify-between">
  <%= link_to 'Simple Airbnb', root_path, class: 'text-xl' %>
  <%= link_to 'Add flat', new_flat_path, class: 'bg-transparent text-blue-500 border border-blue-500 p-2 rounded-md hover:bg-blue-600 hover:text-white' %>
</div>